export enum APP_MODULES {
  USERS = 'USERS',
  HEADQUARTERS = 'HEADQUARTERS',
  USER_AREA = 'USER_AREA',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SETTING = 'SETTING',
  MEMBERSHIP = 'MEMBERSHIP',
  DATA_PARAMETERIZATION = 'DATA_PARAMETERIZATION',
  PATIENT_DATA_SETTINGS = 'PATIENT_DATA_SETTINGS',
  MEDICAL_SPECIALTIES = 'MEDICAL_SPECIALTIES',
  DIAGNOSIS_TYPE = 'DIAGNOSIS_TYPE',
  DIAGNOSIS = 'DIAGNOSIS',
  INDICATIONS_PATIENT = 'INDICATIONS_PATIENT',
  PROCEDURES = 'PROCEDURES',
  HABEAS_DATA = 'HABEAS_DATA',
  INFORMED_CONSENT = 'INFORMED_CONSENT',
  PATIENT_SAFETY_CHECK = 'PATIENT_SAFETY_CHECK',
  LABORATORY_EXAMS = 'LABORATORY_EXAMS',
  MEDICINES = 'MEDICINES',
  PATHOLOGIES = 'PATHOLOGIES',
  
}



